---
- name: Azure 3 tier architecutre
  hosts: localhost
  connection: local
  vars:
    azure_resource_group_name: "demo-rg"
    azure_resource_group_location: "uksouth"
    azure_virtual_network_name: "demo-vnet"
    azure_virtual_network_address: "10.0.0.0/16"
    azure_subnet_name: "demo-snet"
    azure_subnet_address: "10.0.1.0/24"
    azure_publicip_name: "demo-pub-ip"
    azure_security_group_name: "demo-sg"
    azure_network_interface_card_name: "demo-nic"
  tasks:
  - name: create subnet
    azure_rm_subnet:
      resource_group: "{{azure_resource_group_name}}"
      name: "{{azure_subnet_name}}"
      address_prefix: "{{azure_subnet_address}}"
      virtual_network: "{{azure_virtual_network_name}}"

  - name: create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{azure_resource_group_name}}"
      allocation_method: Static
      name: "{{azure_publicip_name}}"
    register: output_ip_address

  - name: create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{azure_resource_group_name}}"
      name: "{{azure_security_group_name}}"
      rules:
        - name: HTTPS
          protocol: TCP
          destination_port_range: 443
          sourceAddressPrefix: "20.30.40.48/30"
          access: Allow
          priority: 1001
          direction: Inbound

  - name: create virtual network interface card
    azure_rm_networkinterface:
      resource_group: "{{azure_resource_group_name}}"
      name: "{{azure_network_interface_card_name}}"
      virtual_network: "{{azure_virtual_network_name}}"
      subnet: "{{azure_subnet_name}}"
      public_ip_name: "{{azure_publicip_name}}"
      security_group: "{{azure_security_group_name}}"

