---
- name: create subnet
  azure_rm_subnet:
    resource_group: "{{azure_resource_group_name}}"
    name: "{{azure_db_subnet_name}}"
    address_prefix: "{{azure_db_subnet_address}}"
    virtual_network: "{{azure_virtual_network_name}}"
  tags: all, db

- name: create Network Security Group that allows SSH
  azure_rm_securitygroup:
    resource_group: "{{azure_resource_group_name}}"
    name: "{{azure_db_security_group_name}}"
    rules:
      - name: allow_app_security_group
        protocol: Tcp
        destination_port_range: 3306
        source_application_security_groups: "{{azure_app_security_group_name}}"
        access: Allow
        priority: 1001
        direction: Inbound
  tags: all, db

- name: create virtual network interface card
  azure_rm_networkinterface:
    resource_group: "{{azure_resource_group_name}}"
    name: "{{azure_db_network_interface_card_name}}"
    virtual_network: "{{azure_virtual_network_name}}"
    subnet: "{{azure_db_subnet_name}}"
    public_ip_name: "{{azure_db_publicip_name}}"
    security_group: "{{azure_security_group_name}}"
  tags: all, db
