---
- name: create subnet
  azure_rm_subnet:
    resource_group: "{{azure_resource_group_name}}"
    name: "{{azure_db_subnet_name}}"
    address_prefix: "{{azure_db_subnet_address}}"
    virtual_network: "{{azure_virtual_network_name}}"
  tags: all, db

- name: create Network Security Group that allows connections from app tier
  azure_rm_securitygroup:
    resource_group: "{{azure_resource_group_name}}"
    name: "{{azure_db_security_group_name}}"
    rules:
      - name: allow_connections_from_app_tier
        protocol: Tcp
        destination_port_range: "{{azure_db_destination_port_rage}}"
        source_address_prefix: "{{azure_app_subnet_address}}"
        access: Allow
        priority: 1001
        direction: Inbound
  tags: all, db

- name: create virtual network interface card
  azure_rm_networkinterface:
    resource_group: "{{azure_resource_group_name}}"
    name: "{{azure_db_network_interface_card_name}}"
    virtual_network: "{{azure_virtual_network_name}}"
    subnet: "{{azure_db_subnet_name}}"
    security_group: "{{azure_db_security_group_name}}"
  tags: all, db
