---
- name: create resource group
  azure_rm_resourcegroup:
    name: "{{azure_resource_group_name}}"
    location: "{{azure_resource_group_location}}"
  tags: all, common

- name: create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{azure_resource_group_name}}"
    name: "{{azure_virtual_network_name}}"
    address_prefixes: "{{azure_virtual_network_address}}"
  tags: all, common